COMP: Fix Camera.cpp build error including "algorithm" required for std::remove
Fix build error like the following reported when
using GCC 9.4.0 on Ubuntu 20.04:

/path/to/Autoscoper/libautoscoper/src/Camera.cpp:397:44: error: cannot convert ‘std::__cxx11::basic_string<char>::iterator’ {aka ‘__gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char> >’} to ‘const char*’
  397 |         value.erase(std::remove(value.begin(), value.end(), ']'), value.end());
      |                                 ~~~~~~~~~~~^~
      |                                            |
      |                                            std::__cxx11::basic_string<char>::iterator {aka __gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char> >}