COMP: Fix unix build expecting TIFF shared library
Since linking against the statically built TIFF library
also requires to explicitly list the "zlib" library as
a dependency, this commit streamline the unix integration
by simply expecting the shared tiff library.

For reference, supporting building against static TIFF
library required the following CMake code to be added
to libautoscoper/CMakeLists.txt:

```
 find_package(TIFF REQUIRED MODULE)
+if(UNIX)
+  # Required to ensure linking against static tiff library.
+  target_link_libraries(TIFF::TIFF INTERFACE -lz)
+endif()
```

And it is intented to fix link errors like the following:

```
[ 46%] Linking CXX executable ../bin/autoscoper
/path/to/Autoscoper-Release/TIFF-install/lib/libtiff.a(tif_pixarlog.c.o):tif_pixarlog.c:function PixarLogVSetField: error: undefined reference to 'deflateParams'
/path/to/Autoscoper-Release/TIFF-install/lib/libtiff.a(tif_pixarlog.c.o):tif_pixarlog.c:function PixarLogCleanup: error: undefined reference to 'inflateEnd'
[...]
/path/to/Autoscoper-Release/TIFF-install/lib/libtiff.a(tif_zip.c.o):tif_zip.c:function ZIPCleanup: error: undefined reference to 'inflateEnd'
/path/to/Autoscoper-Release/TIFF-install/lib/libtiff.a(tif_zip.c.o):tif_zip.c:function ZIPCleanup: error: undefined reference to 'deflateEnd'
```