COMP: Fix windoows build error in Trial.cpp
This commit is a follow-up of 6f86beb (ENH: Support loading & saving
trial config file with relative paths).

It fixes the error reported below specific to Windows where there
are no implicit conversion from std::filesystem::path to std::string.

It turns out there is an implicit conversion from `std::filesystem::path`
to `std::basic_string<value_type>`.

That said, `value_type` is `char` on POSIX and `wchar_t` on Windows.

Since `std::string` corresponds to `std::basic_string<char>`, this
explains the error.

Build error:

Trial.cpp(161,5): error C2440: 'return':
cannot convert from 'std::filesystem::path' to 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>'

Co-authored-by: Jean-Christophe Fillion-Robin <jchris.fillionr@kitware.com>