COMP: Fix build on system only having <experimental/filesystem>
This commit fixes the error reported below by introduing a compatiblity
header adapted from [1] and [2]

[1] https://stackoverflow.com/questions/53365538/how-to-determine-whether-to-use-filesystem-or-experimental-filesystem/53365539#53365539
[2] https://github.com/nlohmann/json/blob/v3.11.2/include/nlohmann/detail/macro_scope.hpp

GCC v7 still does not implement <filesystem> but it does have
the Filesystem Technical Specification which is in
<experimental/filesystem>.

References:
* https://en.cppreference.com/w/cpp/header/experimental/filesystem
* https://en.cppreference.com/w/cpp/header/filesystem

Error:

[ 50%] Building CXX object autoscoper/CMakeFiles/autoscoper.dir/src/net/Socket.cpp.o
/path/to/SlicerAutoscoperM-build/Autoscoper/autoscoper/src/net/Socket.cpp:49:10: fatal error: filesystem: No such file or directory
 #include <filesystem>
          ^~~~~~~~~~~~