COMP: Fix libautoscoper linking against CUDA libraries
This commit fixes a regression introduced in 2adc328 (COMP: Simplify integration
of GPU libraries leveraging transitive usage) that caused the configure error
reported below when doing a "clean" build with the CUDA backend enabled.

The option `CUDA_LINK_LIBRARIES_KEYWORD` introduced in CMake 3.9 is now
set to explicitly ensure a scope keyword is used in `CUDA_ADD_LIBRARY()`.

Configuration error:

```
-- Found CUDA: /usr/local/cuda (found version "10.2")
CMake Error at libautoscoper/CMakeLists.txt:43 (target_link_libraries):
  The plain signature for target_link_libraries has already been used with
  the target "libautoscoper".  All uses of target_link_libraries with a
  target must be either all-keyword or all-plain.

  The uses of the plain signature are here:

   * /usr/local/cmake-3.24.3-linux-x86_64/share/cmake-3.24/Modules/FindCUDA.cmake:1996 (target_link_libraries)
```

This commit also removes the explicit linking to CUDA_LIBRARIES because it
is already done in `CUDA_ADD_LIBRARY()` and keeping it would lead to the
following linking error:

```
[ 47%] Linking CXX executable ../bin/autoscoper
/usr/bin/ld: /usr/local/cuda/lib64/libcudart_static.a(libcudart_static.a.o): undefined reference to symbol 'pthread_rwlock_trywrlock@@GLIBC_2.2.5'
/lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
```