COMP: Fix CUDA RayCaster not having setVisible member
* error C2039: 'setVisible': is not a member of 'xromm::gpu::RayCaster'
* Regression introduced in 103df1a